run CI for macOS and linux

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -5,46 +5,66 @@ on: [push, pull_request]
 env:
   CI: "ON"
   CTEST_TIME_TIMEOUT: "5"  # some failures hang forever
+  HOMEBREW_NO_ANALYTICS: "ON" # Make Homebrew installation a little quicker
+  HOMEBREW_NO_AUTO_UPDATE: "ON"
+  HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK: "ON"
+  HOMEBREW_NO_GITHUB_API: "ON"
+  HOMEBREW_NO_INSTALL_CLEANUP: "ON"
 
 jobs:
   Build:
-    runs-on: windows-latest
+    runs-on: ${{ matrix.os }}
     strategy:
       fail-fast: false
+      matrix:
+        os: [windows-latest, ubuntu-latest, macos-latest]
+    env:
+      FC: gfortran
+      CC: gcc
+      CXX: g++
 
     steps:
-    - uses: actions/checkout@v1
+    - name: checkout code
+      uses: actions/checkout@v1
+
+    - name: Install GFortran for Linux
+      if: contains( matrix.os, 'ubuntu' )
+      run: |
+        sudo apt-get update
+        sudo apt-get install -y gfortran
+
+    - name: install GFortran macOS
+      if: contains( matrix.os, 'macos')
+      run: brew install gcc || brew upgrade gcc || true
 
     - name: build and run
       shell: bash
       working-directory: speedy_ver41.5/run
-
       run: |
         ./run_exp.s t30 201 0 < modify.txt
         ls ../output
 
-      env:
-        FC: gfortran
-        CC: gcc
-        CXX: g++
 
-#    - name: compare output
-#      shell: bash
-#      working-directory: speedy_ver41.5/run
-#      run: |
-#        ./compare.s
+    - name: compare output
+      shell: bash
+      working-directory: speedy_ver41.5/run
+      run: |
+        ./compare.s
 
-    - uses: actions/upload-artifact@v1
-      with:
-        name: atdf201_1979.txt
-        path: speedy_ver41.5/output/exp_201/atdf201_1979.txt
-
-    - uses: actions/upload-artifact@v1
-      with:
-        name: attm201_1979.txt
-        path: speedy_ver41.5/output/exp_201/attm201_1979.txt
-
-    - uses: actions/upload-artifact@v1
-      with:
-        name: atva201_1979.txt
-        path: speedy_ver41.5/output/exp_201/atva201_1979.txt
+#     - uses: actions/upload-artifact@v1
+#       if: failure()
+#       with:
+#         name: atdf201_1979.txt
+#         path: speedy_ver41.5/output/exp_201/atdf201_1979.txt
+# 
+#     - uses: actions/upload-artifact@v1
+#       if: failure()
+#       with:
+#         name: attm201_1979.txt
+#         path: speedy_ver41.5/output/exp_201/attm201_1979.txt
+# 
+#     - uses: actions/upload-artifact@v1
+#       if: failure()
+#       with:
+#         name: atva201_1979.txt
+#         path: speedy_ver41.5/output/exp_201/atva201_1979.txt
